version: '3.1'
services:
  db:
    image: daocloud.io/library/mysql:5.7.17 
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
        - 3306:3306
    volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    - ./data/db:/var/lib/mysql
