version: '2'

services:
    web:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
            - ./code:/code
            - ./cert:/cert
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - code-network
    php:
        image: coll/php:yihua
        container_name: php
        restart: always
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
            - ./code:/code
        networks:
            - code-network
        logging: 
          driver: "json-file"
          options: 
            max-file: '3'
            max-size: "100m"

networks:
    code-network:
        driver: bridge
